config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

dbtvault_greenplum_demo:
  outputs:
    dev:
      type: greenplum
      dbname: postgres
      schema: public
      host: "{{ env_var('DBT_HOST') }}"
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: True
      verify: False
      threads: 3
    # ci:
    #   type: clickhouse
    #   host: clickhouse
    #   port: 8123
    #   schema: default
    #   threads: 4
    dev_local:
      type: greenplum
      dbname: postgres
      schema: otus_dwh
      host: "greenplum7"
      port: 5432
      user: "gpadmin"
      password: "postgres"
      secure: True
      verify: False
      threads: 3
    # ci:
    #   type: clickhouse
    #   host: clickhouse
    #   port: 8123
    #   schema: default
    #   threads: 4
  target: dev
